apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-teste.fullname" . }}
  labels:
    {{- include "app-teste.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-teste.selectorLabels" . | nindent 6 }}  # Corrected indentation
  template:
    metadata:
      labels:
        {{- include "app-teste.selectorLabels" . | nindent 8 }}  # Corrected indentation
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
