# templates/pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "app-teste.fullname" . }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data
