# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-teste.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "app-teste.selectorLabels" . | nindent 4 }}
